### ISSUE TITLE
Invalid transition generated?

### ISSUE THREAD

**Issue by Ghostbird** [arxcruncher/ARM-CFG-from-assembly-generator#1]
I generated a CFG from a simple ARM assembly file, but it seemingly references some invalid nodes:

``` bash
cat myARM.s | ./arm-cfg | dot -Tps -o test.gs
Error: <stdin>: syntax error in line 23 near '->'
```

The line in question is: `node-2 -> node-1;`
However, neither node exists.
What has gone wrong? Is it meant to be: `node2 -> node1;`?

**Comment by srpande** [comment]
It looks like you are generating your assembly from Clang, not from GNU compilers. 

LLVM compiler like clang, will start with basic block 0, where GNU compiler start with 1. That's why you are seeing from -2 to -1, where it should have been 0 to 1. But that's not the entire problem. There are other problems with this code if you compile with LLVM. I will try to fix it.

**Comment by Ghostbird** [comment]
Thanks for the reply, I don't think this is relevant any more though. I got the assembly at that time from a then co-researcher. He worked on Mac, so I guess that's why it's off by one.
